### PR TITLE
Master get storage keys

### PR DESCRIPTION
**Pull request by hppycoder**
Implemented a new feature that will allow a user to get all the keys that the storage system knows of. Use cases for this is when you want to iterate through the keys and get/remove previously used keys in the system.

### CODE REVIEW

**Comment by voronianski** [comment]
@hppycoder man, you completely break the code style :-1:

**Comment by aaunel** [comment]
You'll need to revert the global indentation changes and update this PR.

Indentation changes could be considered, but should be submitted through a new PR. Submitting changes this way masks what the actual code changes are relevant to the feature in context.

**Comment by panuhorsmalahti** [comment]
I'm in favour of the indentation changes (spaces are better than tabs), but like it's been stated that should be a different PR. However, 4 spaces should be used instead of 2, which is the default in jshint/jslint etc.

**Comment by hppycoder** [comment]
I have committed a revert to the whitespace, and set it back to the way it was. I also removed the .jshintrc file along with that because it's not needed. I think getting a .jshintrc file would provide vital as there's currently a mix between tabs and spaces in the file.

That will be a separate PR though.

**Comment by aaunel** [comment]
Cheers @hppycoder , yep I'm not averted to reviewing indentation - especially where there's mixed use of tab and space characters.

The commit that reverts whitespace changes still masks the actual changes. You'll either need to commit an `--amend` to alter the original commit that included indentation changes, or close this PR and submit a new one without masking the PR contents. Sorry! ;)

**Comment by hppycoder** [comment]
@aaunel  - I am seeing the files changed by going to: https://github.com/agrublev/angularLocalStorage/pull/64/files

I will be happy to close this and submit a new one, but I see only the files that I modified. It took github a couple of minutes and refreshes of my browser to catch up with the changes.

**Comment by panuhorsmalahti** [comment]
Yeah, there's no need to make a new PR, and GitHub displays the diff of the merge, not "individual commits". The commits can even be squashed but that's not strictly necessary here.

**Comment by aaunel** [comment]
Cheers, I've always looked at commit messages individually, but that's a much more useful summary!

Cool, can confirm those changes are unmasked. Couple suggestions:

- I'd suggest changing `storage.getStorageKeys()` to `storage.getKeys()`, to reduce repetition.
- Test coverage is slightly too brief, `'should return null for value in localStorage'` is a duplicate of a former test, looks like the assertion hasn't been written. Would be good to also add a test that checks the array of keys being returned matches the keys you set.

With the above, that passes for me.

**Comment by hppycoder** [comment]
@aaunel - Excellent catches and valuable feedback. I have altered the method to ```getKeys()``` instead of ```getStorageKeys()```

I also changed the last assertion description, as it was a copy and paste from the test before it. I have also altered the tests to first evaluate the length of the array and additionally check if the key exists in the array. Could not do ```.toBe(['abcKey','key123'])``` as PhantomJS was inconsistent in the return order.

**Comment by aaunel** [comment]
Awesome, thanks for your contribution, @hppycoder !

Interesting observation around ordering of the keys when requested from localStorage - this may in fact be more prevalent than PhantomJS; not sure how ordering is determined in the spec.

**Comment by hppycoder** [comment]
Thanks for the merge @aaunel, I will generate a new PR for the format change.

It was very peculiar, it has since been fine and behaving itself and possibly I might have been using the wrong jasmine method. Either way it achieves it's goals.

**Pull request merged**
